r_proj_volumetric.name=Proj Volumetric Light
r_proj_volumetric.enable=Enable
r_proj_volumetric.debug=Debug mode
r_proj_volumetric.perspective=Perspective Projected textures
r_proj_volumetric.add=Adding
r_proj_volumetric.ortho_csm=Ortho Projected textures (CSM). Warning! Real CSM create extra lamps. It was reported to devs.
r_proj_volumetric.mul=Multiplier
r_proj_volumetric.add=Adding
r_proj_volumetric.scattering=Scattering
r_proj_volumetric.dist=Near fade dist
r_proj_volumetric.bias=Bias
r_proj_volumetric.noshadows=Volumetric & no shadows
r_proj_volumetric.noshadows.help=Draw Volumetric lights for Projectex textures with disabled shadows.
r_proj_volumetric.view_disabled=Disable debug
r_proj_volumetric.view_colors=View Colors
r_proj_volumetric.view_frustrum=View Frustrum
r_proj_volumetric.quad=Quad downsampling
r_proj_volumetric.quad.help=Require restart. Quad downsampling means ultra downsampling. From 1/16 resolution to native size screen. This means, rendergetet of Volumetric lights will be as 480x270, using 1920x1080 game resolution. Without this params, addon will use half downsampling mode 1/4 size, using 960x540 resolution of rt. You can use it for laptop.
